# Copyright 2020 Hewlett Packard Enterprise Development LP

module "database" {
  source           = "./modules/database_tier"
  datacenter       = "${var.datacenter}"
  datastore        = "${var.datastore}"
  resource_pool    = "${var.resource_pool}"
  vm_cluster_name  = "${var.vm_cluster_name}"
  network          = "${var.network}"
  template         = "${var.template}"
  vsphere_server   = "${var.vsphere_server}"
  vsphere_user     = "${var.vsphere_user}"
  vsphere_password = "${var.vsphere_password}"
  disk_name        = "${var.disk_name}"
  disk_size        = "${var.disk_size}"
  cpu              = "${var.cpu}"
  memory           = "${var.memory}"
  dhcp             = "${var.dhcp}"
  ip_address       = "${var.db_ip_address}"
  netmask          = "${var.netmask}"
  gateway          = "${var.gateway}"
  nameservers      = "${var.nameservers}"
  hostname         = "${var.db_hostname}"
  #proxy            = "${var.proxy}"

}

module "app" {
  source            = "./modules/api_tier"
  db_ip_address     = "${var.db_ip_address}"
  db_instance_id    = "${module.database.db_instance_id}"
  web_ip_address    = "${var.web_ip_address}"
  datacenter        = "${var.datacenter}"
  datastore         = "${var.datastore}"
  resource_pool     = "${var.resource_pool}"
  vm_cluster_name   = "${var.vm_cluster_name}"
  network           = "${var.network}"
  template          = "${var.template}"
  vsphere_server    = "${var.vsphere_server}"
  vsphere_user      = "${var.vsphere_user}"
  vsphere_password  = "${var.vsphere_password}"
  disk_name         = "${var.disk_name}"
  disk_size         = "${var.disk_size}"
  cpu               = "${var.cpu}"
  memory            = "${var.memory}"
  dhcp              = "${var.dhcp}"
  ip_address        = "${var.app_ip_address}"
  netmask           = "${var.netmask}"
  gateway           = "${var.gateway}"
  nameservers       = "${var.nameservers}"
  hostname          = "${var.app_hostname}"
  template_username = "${var.template_username}"
  template_password = "${var.template_password}"
  #proxy             = "${var.proxy}"

}

module "web" {
  source            = "./modules/web_tier"
  app_ip_address    = "${var.app_ip_address}"
  app_instance_id   = "${module.app.app_instance_id}"
  datacenter        = "${var.datacenter}"
  datastore         = "${var.datastore}"
  resource_pool     = "${var.resource_pool}"
  vm_cluster_name   = "${var.vm_cluster_name}"
  network           = "${var.network}"
  template          = "${var.template}"
  vsphere_server    = "${var.vsphere_server}"
  vsphere_user      = "${var.vsphere_user}"
  vsphere_password  = "${var.vsphere_password}"
  disk_name         = "${var.disk_name}"
  disk_size         = "${var.disk_size}"
  cpu               = "${var.cpu}"
  memory            = "${var.memory}"
  dhcp              = "${var.dhcp}"
  ip_address        = "${var.web_ip_address}"
  netmask           = "${var.netmask}"
  gateway           = "${var.gateway}"
  nameservers       = "${var.nameservers}"
  hostname          = "${var.web_hostname}"
  template_username = "${var.template_username}"
  template_password = "${var.template_password}"
  #proxy             = "${var.proxy}"

}